name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name: SSH into Hostinger VPS
       uses: invi5H/ssh-action@v1
       with:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
       env:
          SERVER: /var/www/  # Set the server directory where you want to execute the command
          REPO_URL: https://github.com/kareemi55/hostinger.git
        
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
          node-version: 18

     - name: Install dependencies
       run: |
          cd /var/www/hostinger/server
          npm install -f
          cd ../client
          npm install -f

     - name: Build React app
       run: |
          cd client
          CI= npm run build


            
            # Restart your Node.js server (assuming you're using Node.js to run your server)
            pm2 restart front-end
            pm2 restart server 
            systemctl restart apache2
