name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd server
          npm install -f
          cd ../client
          npm install -f

      - name: Build React app
        run: |
          cd client
          CI= npm run build

      - name: Deploy to Hostinger VPS
        uses: invi5H/ssh-action@v1
        
        with:
          SSH_HOST: ${{ secrets.HOSTINGER_HOST }}
          SSH_USER: ${{ secrets.HOSTINGER_USERNAME }}
          SSH_KEY: ${{ secrets.HOSTINGER_PASSWORD }}
          SSH_PORT: ${{ secrets.HOSTINGER_SSH_PORT }}  # Use the appropriate SSH port
        env:
          SERVER: /var/www/ 
          script: |
            ssh ${{ steps.ssh.outputs.SERVER }} 
            
            # Pull the latest changes from your Git repository
            git pull origin main
            
            # Restart your Node.js server (assuming you're using Node.js to run your server)
            pm2 restart front-end
            pm2 restart server 
