name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Hostinger VPS
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.HOSTINGER_HOST }}
          SSH_PORT: ${{ secrets.HOSTINGER_SSH_PORT }}
          SSH_USER: ${{ secrets.HOSTINGER_USERNAME }}
          SSH_KEY: ${{ secrets.HOSTINGER_PASSWORD }}
      
      - name: Check SSH Connection
        run: |
          # Run a simple command on the server to verify the connection
          ssh -p ${{ secrets.HOSTINGER_SSH_PORT }} ${{ secrets.HOSTINGER_USERNAME }}@${{ secrets.HOSTINGER_HOST }} "echo 'Connected to the server'"

      - name: Clone Git repository to /var/www/
        run: |
          # Clone the Git repository to /var/www/hostinger/
          git clone https://github.com/kareemi55/hostinger.git /var/www/hostinger/

      - name: Pull latest changes
        run: |
          # Change the working directory to /var/www/hostinger/
          cd /var/www/hostinger/

          # Pull the latest changes from the Git repository
          git pull origin main

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd /var/www/hostinger/server
          npm install -f
          cd ../client
          npm install -f

      - name: Build React app
        run: |
          cd client
          CI= npm run build

      - name: Restart Node.js server
        run: |
          pm2 restart front-end
          pm2 restart server
          systemctl restart apache2
