name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOSTINGER_HOST }}    # Update with your HOSTINGER_HOST secret
        USERNAME: ${{ secrets.HOSTINGER_USERNAME }}  # Update with your HOSTINGER_USERNAME secret
        PORT: ${{ secrets.HOSTINGER_SSH_PORT }}  # Update with your HOSTINGER_SSH_PORT secret
        KEY: ${{ secrets.HOSTINGER_PASSWORD }}  # Update with your HOSTINGER_PASSWORD secret
      with:
        source: "."
        target: "/var/www/hostinger"  # Update with your target directory on the server

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}  # Update with your HOSTINGER_HOST secret
        USERNAME: ${{ secrets.HOSTINGER_USERNAME }}  # Update with your HOSTINGER_USERNAME secret
        PORT: ${{ secrets.HOSTINGER_SSH_PORT }}  # Update with your HOSTINGER_SSH_PORT secret
        KEY: ${{ secrets.HOSTINGER_PASSWORD }}  # Update with your HOSTINGER_PASSWORD secret
        script: ls
