name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: connecting to server
      run: |
       ssh -T root@154.56.56.150

    - name: creating a directory
      run: |
       sudo mkdir /var/www/testing
     
