name: Connect to Server and Create Folder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH key
      run: echo "${{ secrets.HOSTINGER_KEY }}" > ~/.ssh/id_rsa
      env:
        SSH_KEY: ${{ secrets.HOSTINGER_KEY }}

    - name: Add SSH key to known_hosts
      run: ssh-keyscan -H ${{ secrets.HOSTINGER_HOST }} >> ~/.ssh/known_hosts
      env:
        HOST: ${{ secrets.HOSTINGER_HOST }}

    - name: Connect to server and create folder
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.HOSTINGER_USERNAME}}@${{ secrets.HOSTINGER_HOST }} "sudo mkdir -p /var/www/myfolder"
      env:
        SSH_USER: your_ssh_username
        HOST: your_server_ip_or_hostname
        SSH_KEY: ${{ secrets.HOSTINGER_KEY }}
