name: Connect to Server and Create Folder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.HOSTINGER_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_KEY: ${{ secrets.HOSTINGER_KEY }}

    - name: Add SSH key to known_hosts
      run: ssh-keyscan -H ${{ secrets.HOSTINGER_HOST }} >> ~/.ssh/known_hosts
      env:
        HOST: ${{ secrets.HOSTINGER_HOST }}

    - name: Connect to server 
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.HOSTINGER_USERNAME }}@${{ secrets.HOSTINGER_HOST }} << EOF
        cd var/www/
        git clone https://github.com/kareemi55/hostinger.git
        EOF
