name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Add SSH key to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 154.56.56.150 >> ~/.ssh/known_hosts
      # Important: Replace 154.56.56.150 with your actual server's IP address or hostname.

    - name: connecting to server
      run: |
        ssh -T root@154.56.56.150
      # Important: Replace 154.56.56.150 with your actual server's IP address or hostname.

    - name: creating a directory
      run: |
        sudo mkdir /var/www/testing
